config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('new_app.urls', namespace='new_app')),
    path('materials/', include('materials.urls', namespace='materials')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materials/urls.py
from django.urls import path
from materials.apps import MaterialsConfig
from materials.views import (MaterialCreateView, MaterialListView, MaterialDetailView, MaterialUpdateView,
                             MaterialDeleteView)

app_name = MaterialsConfig.name

urlpatterns = [
    path('create/', MaterialCreateView.as_view(), name='create'),
    path('', MaterialListView.as_view(), name='list'),
    path('view/<int:pk>', MaterialDetailView.as_view(), name='view'),
    path('edit/<int:pk>', MaterialUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', MaterialDeleteView.as_view(), name='delete'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

materials/models.py
from django.db import models

class Material(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название')
    body = models.TextField(verbose_name='Содержимое')

    views_count = models.IntegerField(default=0, verbose_name='просмотры')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Материал'
        verbose_name_plural = 'Материалы'

materials/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from materials.models import Material


class MaterialCreateView(CreateView):
    model = Material
    fields = ('title', 'body')
    success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)


class MaterialUpdateView(UpdateView):
    model = Material
    fields = ('title', 'body')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('materials:view', args=[self.kwargs.get('pk')])


class MaterialListView(ListView):
    model = Material

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class MaterialDetailView(DetailView):
    model = Material

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class MaterialDeleteView(DeleteView):
    model = Material
    success_url = reverse_lazy('materials:list')

materials/templates/materials/material_confirm_delete.html
{% extends 'new_app/base.html' %}

{% block content %}
<div class="col-12 mb-5">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить материал "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'materials:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

materials/templates/materials/material_detail.html
{% extends 'new_app/base.html'%}
{% block content %}
<div class="col-12 mb-5">
    <div class="row">
        <div class="col-6">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <p class="card-text">Материал:
                        {{ object.title }} ({{ object.slug }})
                    </p>
                    <p class="card-text">Содержание:
                        {{ object.body }}
                    </p>
                </div>
                <div class="card-footer">
                    Просмотры {{ object.views_count }}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-12 mb-5">
        <a class="btn btn-outline-secondary" href="{% url 'materials:list' %}" role="button">Назад</a>
</div>
{% endblock %}

materials/templates/materials/material_form.html
{% extends 'new_app/base.html' %}

{% block content %}
<div class="col-12 mb-5">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-12 mb-5">
        <a class="btn btn-outline-secondary" href="{% url 'materials:list' %}" role="button">Назад</a>
</div>

{% endblock %}

materials/templates/materials/material_list.html
{% extends 'new_app/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'materials:create' %}">Добавить материал</a>
</div>

{% for object in object_list %}
<div class="col">
    <div class="card shadow-sm">
        <div class="card-body">
            <p class="card-text">Материал:
                {{ object|title }}
            </p>
            <p class="card-text">Содержание:
                {{ object.body }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a class="btn btn-outline-info" href="{% url 'materials:view' object.pk %}"
                       role="button">Просмотр</a>
                    <a class="btn btn-outline-info" href="{% url 'materials:edit' object.pk %}"
                       role="button">Редактировать</a>
                    <a class="btn btn-outline-info" href="{% url 'materials:delete' object.pk %}"
                       role="button">Удалить</a>
                </div>
                <small class="text-body-secondary"></small>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}