config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('new_app.urls', namespace='new_app')),
    path('materials/', include('materials.urls', namespace='materials')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

new_app/urls.py
from django.urls import path
from new_app.apps import NewAppConfig
from new_app.views import (contact, StudentListView, StudentDetailView, StudentCreateView, StudentUpdateView,
                           StudentDeleteView, toggle_activity)

app_name = NewAppConfig.name

urlpatterns = [
    #path('', index, name='index'),
    path('', StudentListView.as_view(), name='index'),
    path('contact/', contact, name='contact'),
    path('view/<int:pk>/', StudentDetailView.as_view(), name='student_detail'),
    path('create/', StudentCreateView.as_view(), name='create_student'),
    path('edit/<int:pk>/', StudentUpdateView.as_view(), name='update_student'),
    path('delete/<int:pk>/', StudentDeleteView.as_view(), name='delete_student'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

new_app/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}

class Student(models.Model):

    first_name = models.CharField(max_length=100, verbose_name='Имя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия')
    avatar = models.ImageField(upload_to='students/', verbose_name='аватар', **NULLABLE) # 2 Вариант
    # avatar = models.ImageField(upload_to='students/', verbose_name='аватар', null=True, blank=True) # 1 Вариант
    # null=True значит что мы можем хранить в базе null объекты (пустыне)
    # blank=True значит что мы можем хранить в базе пустые строки

    email = models.CharField(max_length=150, verbose_name='email', unique=True, **NULLABLE)

    is_active = models.BooleanField(default=True, verbose_name='Учится')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


    class Meta:
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'
        ordering = ('last_name',)
        # Информация для вывода удобного отображения текстов нашей модели


class Subject(models.Model):
    title = models.CharField(max_length=150, verbose_name='название')
    description = models.TextField(verbose_name='описание')
    students = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name='студенты')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Предмет'
        verbose_name_plural = 'Предметы'

new_app/forms.py
from django import forms

from new_app.models import Student, Subject


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class StudentForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Student
        # fields = '__all__'
        fields = ('first_name', 'last_name', 'avatar', 'email')
        # exclude = ('is_active')

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     for field_name, field in self.fields.items():
    #         field.widget.attrs['class'] = 'form-control'


    def clean_email(self):
        cleaned_data = self.cleaned_data['email']
        if 'sky.pro' not in cleaned_data:
            raise forms.ValidationError('Не правильный email')
        return cleaned_data


class SubjectForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Subject
        fields = '__all__'

new_app/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from new_app.forms import StudentForm, SubjectForm
from new_app.models import Student, Subject
from django.urls import reverse_lazy, reverse


class StudentListView(ListView):
    model = Student
    # template_name = 'new_app/index.html'


class StudentDetailView(DetailView):
    model = Student
    # template_name = 'new_app/student_detail.html'


class StudentCreateView(CreateView):
    model = Student
    form_class = StudentForm
    success_url = reverse_lazy("new_app:index")


class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentForm
    success_url = reverse_lazy("new_app:index")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(Student, Subject, form=SubjectForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = SubjectFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = SubjectFormset(instance=self.object) #instance=self.object
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

class StudentDeleteView(DeleteView):
    model = Student
    success_url = reverse_lazy("new_app:index")


def toggle_activity(request, pk):
    student_item = get_object_or_404(Student, pk=pk)
    if student_item.is_active:
        student_item.is_active = False
    else:
        student_item.is_active = True

    student_item.save()

    return redirect(reverse("new_app:index"))



# def view_student(request, pk):
#     student_item = get_object_or_404(Student, pk=pk)
#     context = {
#        'student': student_item,
#     }
#     return render(request, 'new_app/student_detail.html', context)

# def index(request):
#     students_list = Student.objects.all()
#     context = {
#         'object_list': students_list,
#         'title': 'Student List',
#     }
#     return render(request, 'new_app/index.html', context)



def contact(request):
    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        message = request.POST.get("message")
        print(f'{name} ({email}: {message})')
    context = {'title': 'Контакты'}
    return render(request, 'new_app/contact.html', context)

new_app/templates/new_app/base.html
{% load static %}
<!doctype html>
<html lang="ru" data-bs-theme="auto">
<head>
    <meta charset="utf-8">

    <title>{{ title }}</title>

    <link rel="canonical" href="https://bootstrap-4.ru/docs/5.3/examples/album/">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">


</head>
<body>

<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                {% include 'new_app/includes/inc_main_menu.html' %}
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">{{ title }}</h1>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p>&copy; 2023 - {% now 'Y' %}</p>
    </div>
</footer>

<script src="/docs/5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.j' %}"></script>
</body>
</html>

new_app/templates/new_app/contact.html
{% extends 'new_app/base.html' %}

{% block content %}
<div class="col-md-4">
    <div class="card shadow-sm">
        <div class="card-body">
            <p class="card-text">
                Office Moscow<br>
                Office Spb
            </p>
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="card shadow-sm">
        <div class="card-body">
            <h2> Напишите нам </h2>
            <form method="post">
                {% csrf_token %}
                <input class="form-control mb-2" name="name"/>
                <input class="form-control mb-2" name="email"/>
                <textarea class="form-control mb-2" name="message"></textarea>
                <button type="submit" class="btn btn-primary form-control mb-2">Отправить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

new_app/templates/new_app/index.html
{% extends 'new_app/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="#">Добавить студента</a>
</div>
    {% for object in object_list %}
    <div class="col">
        <div class="card shadow-sm">
            <div class="card-body">
                <p class="card-text">
                    {% if object.is_active %}
                    {{ object|title }}
                    {% else %}
                    <span class="text-muted">{{ object|title }}</span>
                    {% endif %}
                </p>
               <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a class="btn btn-outline-info" href="{% url 'new_app:student_detail' object.pk %}"
                       role="button">Просмотр</a>
                    <a class="btn btn-outline-info"
                       role="button">Edit</a>
                    <a class="btn btn-outline-info"
                       role="button">Delete</a>
                </div>
                    <small class="text-body-secondary"></small>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}

new_app/templates/new_app/student_confirm_delete.html
{% extends 'new_app/base.html' %}

{% block content %}
<div class="col-12 mb-5">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить студента "{{ object.first_name }} {{ object.last_name }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'new_app:index' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

new_app/templates/new_app/student_detail.html
{% extends 'new_app/base.html'%}
{% block content %}
<div class="col-12 mb-5">
    <div class="row">
        <div class="col-3">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <p class="card-text">Имя: {{ object.first_name }}</p>
                    <p class="card-text">Фамилия: {{ object.last_name }}</p>
                </div>
            </div>
        </div>
        <div class="col-3">
            <img src="/media/{{object.avatar}}" style="object-fit: cover; width: 100%; height: 50%"/>
        </div>
    </div>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-secondary" href="{% url 'new_app:index' %}"
       role="button">Назад</a>
</div>
{% endblock %}

new_app/templates/new_app/student_form.html
{% extends 'new_app/base.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="col mb-5">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Добавление студента</h5>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                             {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Предметы студента</h5>
                    </div>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p }}
                            {% if not forloop.last %}
                                <hr>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<div class="col-12 mb-5">
    <a class="btn btn-outline-secondary" href="{% url 'new_app:index' %}"
       role="button">Назад</a>
</div>
{% endblock %}

new_app/templates/new_app/student_list.html
{% extends 'new_app/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'new_app:create_student' %}">Добавить студента</a>
</div>
    {% for object in object_list %}
<div class="col-4 mb-5">
    <div class="card shadow-sm">
        <div class="card-body">
            <p class="card-text">
                {% if object.is_active %}
                {{ object|title }}
                {% else %}
                <span class="text-muted">{{ object|title }}</span>
                {% endif %}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a class="btn btn-outline-info" href="{% url 'new_app:student_detail' object.pk %}"
                       role="button">View</a>
                    <a class="btn btn-outline-info" href="{% url 'new_app:update_student' object.pk %}"
                       role="button">Edit</a>
                    <a class="btn btn-outline-info" href="{% url 'new_app:delete_student' object.pk %}"
                       role="button">Delete</a>
                </div>
                {% if object.is_active %}
                <a class="btn btn-warning" href="{% url 'new_app:toggle_activity' object.pk %}">Деактивировать</a>
                {% else %}
                <a class="btn btn-success" href="{% url 'new_app:toggle_activity' object.pk %}">Активировать</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
    {% endfor %}

{% endblock %}